name: Build Cheat Engine

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Lazarus
      run: |
        # Download Lazarus using Invoke-WebRequest
        Invoke-WebRequest -Uri "https://sourceforge.net/projects/lazarus/files/Lazarus%20Windows%2064%20bits/Lazarus%202.2.2/lazarus-2.2.2-fpc-3.2.2-win64.exe" -OutFile "lazarus-2.2.2-fpc-3.2.2-win64.exe"
        # Install Lazarus
        ./lazarus-2.2.2-fpc-3.2.2-win64.exe


    - name: Build with Lazarus
      run: |
        # Build the project using Lazarus
        # This is a placeholder command and might need adjustments
        lazbuild cheatengine.lpi

    - name: Upload Binary as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: cheat-engine-binary
        path: bin/cheat-engine.exe  # Adjust this path to where the binary is generated

